apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: argocd
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: nginx-service
      previewService: nginx-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.12.3  # 更新镜像版本时修改这里
          ports:
            - containerPort: 80
