apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-bluegreen
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: nginx-service
      previewService: nginx-preview
      autoPromotionSeconds: 60
      scaleDownDelaySeconds: 30
      # Optional: you can add a rollout analysis or metric provider here
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
